server:
  port: 8099

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://192.168.230.48:3307/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://mysql:3309/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 2648
  redis:
    host: redis
    port: 6380
    database: 0
#    cluster:
#      nodes:
#        - 192.168.230.48:6381
#        - 192.168.230.48:6382
#        - 192.168.230.48:6383
#        - 192.168.230.48:6384
#        - 192.168.230.48:6385
#        - 192.168.230.48:6386
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  swagger2:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.li.docker.domain